# Generated by Django 2.2.1 on 2019-05-24 09:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('classcrud', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classblog',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='classblog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='classblog',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
